from Cache.LRU.LRU import LRU

lru = LRU(4)
lru.set_value(1)
lru.set_value(2)
lru.set_value(3)
lru.set_value(4)
lru.set_value(5)
lru.set_value(6)
lru.set_value(7)
lru.set_value(8)
lru.set_value(9)
lru.set_value(10)
lru.set_value(11)
lru.set_value(12)
lru.set_value(9)
lru.set_value(13)
lru.set_value(1)
lru.set_value(2)
lru.set_value(3)
lru.set_value(13)
lru.set_value(14)
lru.set_value(15)
lru.set_value(14)
lru.display_cache()